server:
  port: 8080

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: redis
      port: 6379
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<path>.*), /$\{path}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<path>.*), /$\{path}
        - id: dispatch-service
          uri: lb://dispatch-service
          predicates:
            - Path=/dispatch-service/**
          filters:
            - RewritePath=/dispatch-service/(?<path>.*), /$\{path}
        - id: user-service
          uri: lb://user-management-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}
        - id: role-permission-service
          uri: lb://user-management-service
          predicates:
            - Path=/role-permission-service/**
          filters:
            - RewritePath=/role-permission-service/(?<path>.*), /$\{path}
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/user-management-service/**
          filters:
            - RewritePath=/user-management-service/(?<path>.*), /$\{path}
        - id: b2b-bff-service
          uri: lb://unified-bff-service
          predicates:
            - Path=/api/b2b/**
          filters:
            - RewritePath=/api/b2b/(?<path>.*), /$\{path}
        - id: b2c-bff-service
          uri: lb://unified-bff-service
          predicates:
            - Path=/api/b2c/**
          filters:
            - RewritePath=/api/b2c/(?<path>.*), /$\{path}
        - id: mobile-bff-service
          uri: lb://unified-bff-service
          predicates:
            - Path=/api/mobile/**
          filters:
            - RewritePath=/api/mobile/(?<path>.*), /$\{path}
        - id: unified-bff-service
          uri: lb://unified-bff-service
          predicates:
            - Path=/unified-bff-service/**
          filters:
            - RewritePath=/unified-bff-service/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
