spring.application.name=integration-service
server.port=8107

# Database Configuration
spring.datasource.url=jdbc:postgresql://postgres-db:5432/integration_db
spring.datasource.username=logistics_user
spring.datasource.password=logistics_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka Configuration
eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
eureka.instance.prefer-ip-address=true
