spring:
  application:
    name: routing-service
  
server:
  port: 8095

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    com.logistics.routing: DEBUG
