version: '3.8'

services:
  # ==================== B2C Engine ====================
  parcel-service:
    build: ../b2c-engine/parcel-service
    image: logistics/parcel-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on: [ config-server, service-discovery, postgres ]
    networks: [ logistics-network ]

  # ==================== Mobile Backend ====================
  customer-api-service:
    build: ../mobile-backend/customer-api-service
    image: logistics/customer-api-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on: [ config-server, service-discovery, postgres ]
    networks: [ logistics-network ]

  driver-api-service:
    build: ../mobile-backend/driver-api-service
    image: logistics/driver-api-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on: [ config-server, service-discovery, postgres ]
    networks: [ logistics-network ]

networks:
  logistics-network:
    external: true
