version: '3.8'

services:

  logistic-app:
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ..:/app
    networks:
      - logistics-network

  # Development tools
  mailhog:
    image: mailhog/mailhog:latest
    container_name: logistics-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - logistics-network
