spring:
  application:
    name: platform-core

  datasource:
    url: jdbc:mysql://mysql-db:3306/logistics_core_db
    username: logistics_user
    password: logistics_pass

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

logging:
  level:
    com.logistics.platform: DEBUG