server:
  port: 8097

spring:
  application:
    name: tracking-service
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
  cloud:
    function:
      definition: processDriverLocations;processHeatmap
    stream:
      bindings:
        processDriverLocations-in-0:
          destination: fleet.driver-updates
        processDriverLocations-out-0:
          destination: tracking.events
        processHeatmap-in-0:
          destination: tracking.events
        processHeatmap-out-0:
          destination: market.heatmap

