spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  application:
    name: Auth Service
  config:
    import: "optional:configserver:http://localhost:8888/"
