spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  application:
    name: auth-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}"

  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
