spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_db
    username: logistics_user
    password: logistics_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
